# Setup gradle memory
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.caching=true

mod_version=1.4.x
minecraft_version=1.21.1
neo_version=21.1.228

neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17
neogradle.subsystems.conventions.sourcesets.automatic-inclusion-test=true
